### ISSUE TITLE
Terser 5 meta-issue

### ISSUE THREAD

**Issue by fabiosantoscode** [terser/terser#700]
- [x] Change `-b` to `-f` while keeping backwards compatibility
 - [x] Distribute as ESM package without default export
 - [x] Support only node 10+
 - [ ] Change argument order, such that you can use `terser foo.js -mc` as well as `terser -mc foo.js`
 - [x] Do not expose internal AST anymore
 - [x] Do not mutate options
 - [x] Ship alpha versions to let people test things out
 - [x] Do not expose internal APIs
 - [x] Make minify() async and throw error instead of returning it

**Comment by LongTengDao** [comment]
What does "Distribute as ESM package without default export" mean?

**Comment by fabiosantoscode** [comment]
Right now Terser is distributed as a commonJS package. Terser 5 will be distributed as a commonJS + ESM package. The ESM version will not have a default export. IE, you will `import { minify } from 'terser'`, but not `import Terser from 'terser'`.

If you store your options in a variable, then call `minify(options)`, you will see that Terser mutated your object. Besides the propmangle cache, this shouldn't happen.

There are some exports in Terser which are public, such as `default_options`, which is meant for try.terser.org and tests. These exports will all start with a `_`, indicating that you shouldn't access them (you can, but please don't).

**Comment by LongTengDao** [comment]
Nice!

**Comment by LongTengDao** [comment]
BTW: What does "propmangle cache" mean?

**Comment by fabiosantoscode** [comment]
It's just the cache for the property mangler.

**Comment by evilebottnawi** [comment]
> Do not expose internal AST anymore
> Do not mutate options

Awesome :smile:

**Comment by fabiosantoscode** [comment]
@evilebottnawi I hate split packages, and commander is very small anyway.

I would love to do a small change to the CLI, where one can pass options before, or after filenames. But that's not a breaking change.

**Comment by shadowspawn** [comment]
> Change argument order, such that you can use terser foo.js -mc as well as terser -mc foo.js

> I would love to do a small change to the CLI, where one can pass options before, or after filenames. But that's not a breaking change.

Light question, do you already have an idea for how to achieve that? 

(There are awkward parsing ambiguities when filenames are mixed with options which have optional values. I am intrigued how you might solve this in a non-breaking way.)

**Comment by fabiosantoscode** [comment]
I haven't given it much thought yet. But you're totally right. Geez, parsing arguments sucks!

**Comment by fabiosantoscode** [comment]
npm install terser@beta -- have a go!

**Comment by fabiosantoscode** [comment]
Terser 5 has been released, have a go!
